### ISSUE TITLE
Change default Taskwarrior-installation default install location

### ISSUE THREAD

**Issue by linuxcaffe** [HiveMinds-EU/Taskwarrior-installation#80]
Hi @a-t-0 ! IMHO, rather than cloning to an arbitrary location, to install Taskwarrior-installation, I think it should land under the .task directory, and (as per pull request) I took the liberty of changing the target folder name to "install".

**Comment by a-t-0** [comment]
Thank you for the suggestion, and for making the pull request, it has been merged into the main branch.
